 == Class to learn about numpy arrays==

**Numpy**: Numeric computing library 
NumPya(Numerical Python) is one of the core package for numerical computing in python

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)



    
## Basic NumPy Arrays 

In [52]:
import numpy as np
import pandas as pd

#Create numpy array 
a = np.array([2,4,6,7,8,9])
#convert int array into String array
a1 = a.astype(str)
print(a1)
print("Print First and Last value from array: ") 
a[0],a[-1]



['2' '4' '6' '7' '8' '9']
Print First and Last value from array: 


(2, 9)

In [53]:
#use slice to print array from respective index to respective index
a[0:3]

array([2, 4, 6])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array Types

In [54]:
b = np.array([1,3,5,7,9])
# print type of the array 
b.dtype


dtype('int32')

In [55]:
#print data type for the array which contains float values
Floatc = np.array([0.5,2.5,5.5])
Floatc.dtype

dtype('float64')

In [56]:
#change the array size 
np.array([2,3,4,6], dtype=np.int8)

array([2, 3, 4, 6], dtype=int8)

In [57]:
np.array(['a','b','c'])

array(['a', 'b', 'c'], dtype='<U1')

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Dimensions and Shapes

In [58]:
#create 2 dimensional array 
twoD = np.array([
    [2,4,6],
    [2,5,7]
])
#print the size of 2D array
twoD.size


6

In [59]:
#Print number of dimensions
twoD.ndim

2

In [60]:
#print shape of the array - Rows and Colomn
twoD.shape

(2, 3)

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Indexing and Slicing of Matrices

In [62]:
#Square Matrix
C = np.array([
#.   0.1.2.3     
    [2,3,4,5], #0
    [7,8,9,0], #1
    [2,1,5,3]  #2
])
#print first row of matrix
C[0]

array([2, 3, 4, 5])

In [63]:
#print 2nd element in the first row
C[0][1]

3

In [ ]:
#use slice in multidimensinal array
C[0:2]