 == Class to learn about numpy arrays==

**Numpy**: Numeric computing library 
NumPya(Numerical Python) is one of the core package for numerical computing in python

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)



    
## Basic NumPy Arrays 

In [92]:
import numpy as np
import pandas as pd

#Create numpy array 
a = np.array([2,4,6,7,8,9])
#convert int array into String array
a1 = a.astype(str)
print(a1)
print("Print First and Last value from array: ") 
a[0],a[-1]



['2' '4' '6' '7' '8' '9']
Print First and Last value from array: 


(2, 9)

In [93]:
#use slice to print array from respective index to respective index
a[0:3]

array([2, 4, 6])

ss

In [94]:
b = np.array([1,3,5,7,9])
# print type of the array 
b.dtype


dtype('int32')

In [95]:
#print data type for the array which contains float values
Floatc = np.array([0.5,2.5,5.5])
Floatc.dtype

dtype('float64')

In [96]:
#change the array size 
np.array([2,3,4,6], dtype=np.int8)

array([2, 3, 4, 6], dtype=int8)

In [97]:
np.array(['a','b','c'])

array(['a', 'b', 'c'], dtype='<U1')

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Dimensions and Shapes

In [98]:
#create 2 dimensional array 
twoD = np.array([
    [2,4,6],
    [2,5,7]
])
#print the size of 2D array
twoD.size


6

In [99]:
#Print number of dimensions
twoD.ndim

2

In [100]:
#print shape of the array - Rows and Colomn
twoD.shape

(2, 3)

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Indexing and Slicing of Matrices

In [101]:
#Square Matrix
C = np.array([
#.   0.1.2.3     
    [2,3,4,5], #0
    [7,8,9,0], #1
    [2,1,5,3]  #2
])
#print first row of matrix
C[0]

array([2, 3, 4, 5])

In [102]:
#print 2nd element in the first row
C[0][1]

3

In [103]:
#use slice in multidimensinal array
#print fist two rowa
C[0:2]

array([[2, 3, 4, 5],
       [7, 8, 9, 0]])

In [104]:
#print first colomn
C[:,0]

array([2, 7, 2])

In [105]:
#change the values of the array
C[1] = np.array([4, 4, 4, 4])
C

array([[2, 3, 4, 5],
       [4, 4, 4, 4],
       [2, 1, 5, 3]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary Statistics

In [106]:
#add values in the array
d = np.array([2,4,6,8])
d.sum()

20

In [107]:
#print mean of the array
d.mean()

5.0

In [108]:
#print standard deviation of the array 
d.std()

2.23606797749979

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Broadcasting and Vectorized operations